### ISSUE TITLE
Tombol logout

### ISSUE THREAD

**Issue by putridinar** [daffadevhosting/Jekyll-Ionic_onlinestore#1]
Mass. Da dasboard admin belum ada tombol buat logout yahhh?!

**Comment by daffadevhosting** [comment]
> Mass. Da dasboard admin belum ada tombol buat logout yahhh?!

Belum neng. lupa...

**Comment by putridinar** [comment]
> > Mass. Da dasboard admin belum ada tombol buat logout yahhh?!
> 
> Belum neng. lupa...

Ouhg.. awas lupanya sampe selesai..

**Comment by daffadevhosting** [comment]
> > > Mass. Da dasboard admin belum ada tombol buat logout yahhh?!
> > 
> > 
> > Belum neng. lupa...
> 
> Ouhg.. awas lupanya sampe selesai..

ngga, sudah saya pasang tombol logout nya yah...
